name: Pull Request to master branch
run-name: Run by @${{ github.actor }}

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  testing:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Pods Cache
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: CocoaPods Install
        run: |
          cd iOS-CiCd-CodeMagic
          pod install

      - name: Run Tests
        run: |
            cd iOS-CiCd-CodeMagic
            xcodebuild -workspace iOS-CiCd-CodeMagic.xcworkspace -scheme BBL -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' test  
